CREATE TABLE MEMBER2(
ID VARCHAR2(40) PRIMARY KEY,
NAME VARCHAR2(40) NOT NULL,
PASSWORD VARCHAR2(40) NOT NULL);

INSERT INTO MEMBER2 VALUES('GREENTEA2','GREEN','TEA');
INSERT INTO MEMBER2 VALUES('ASD','RED','BLUE');
COMMIT;
SELECT * FROM MEMBER2;